version: "3.1"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "0.0.0.0:4566:4566"            # LocalStack Gateway
      - "0.0.0.0:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3, iam, lambda, dynamodb, cloudwatch
      - DEBUG=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_ACCESS_KEY_ID="test"
      - AWS_SECRET_ACCESS_KEY="test"
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  web:
    image: nginx
    volumes:
      - ./lstc-web/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./lstc-web/dist:/app
    ports:
      - 80:80
    command: [ nginx-debug, '-g', 'daemon off;' ]
